"""moving random seed and test size from experiments to training runs

Revision ID: 61de99c3fd58
Revises: c87939bd5e87
Create Date: 2026-08-28 11:20:51.687800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61de99c3fd58'
down_revision: Union[str, Sequence[str], None] = 'c87939bd5e87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiments', 'random_seed')
    op.drop_column('experiments', 'test_size')
    op.add_column('training_runs', sa.Column('test_size', sa.Float(), nullable=False))
    op.add_column('training_runs', sa.Column('random_seed', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_runs', 'random_seed')
    op.drop_column('training_runs', 'test_size')
    op.add_column('experiments', sa.Column('test_size', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('experiments', sa.Column('random_seed', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
